Prepare networks for Algorand

diff --git a/script/remote/deploy-algorand-worker b/script/remote/deploy-algorand-worker
--- a/script/remote/deploy-algorand-worker
+++ b/script/remote/deploy-algorand-worker
@@ -15,6 +15,7 @@ set -e
 script_name='deploy-algorand-worker'
 install_root="${HOME}/install/algorand"
 deploy_root="${HOME}/deploy/algorand"
+prepare_root="${HOME}/prepare/algorand"
 
 
 # Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -58,8 +59,14 @@ prepare() {
 	fatal "unexpected operand '$1'"
     fi
 
-    if [ ! -d "${deploy_root}" ] ; then
+    if [ -e "${deploy_root}" ] ; then
+	rm -rf "${deploy_root}"
+    fi
+
 	mkdir -p "${deploy_root}"
+
+    if [ ! -d "${prepare_root}" ] ; then
+	mkdir -p "${prepare_root}"
     fi
 }
 
@@ -189,7 +196,7 @@ generate_chainconfig() {
 
     nodenum=$(cat "${nodefile}" | wc -l)
 
-    algorand-chainfile-generator "${netroot}" "${nodenum}" "${deploy_root}/accounts.yaml"
+    algorand-chainfile-generator "${netroot}" "${nodenum}" "${netroot}/accounts.yaml"
 }
 
 # Generate an Algorand testnet specification in "$deploy_root/network" and a
@@ -226,22 +233,30 @@ generate() {
 	rm -rf "${netroot}"
     fi
 
-    if ! goal network create --rootdir "${netroot}" --network 'private' \
-	 --template "${template}" > "${logfile}" ; then
-	cat "${logfile}"
-	fatal "cannot generate network in '${netroot}'"
-    fi
+    local numnode=$(cat "${nodefile}" | wc -l)
+    local prepared_path="${prepare_root}/network-${numnode}"
 
-    kill_kmd_processes "${netroot}"
+    if [ ! -e "${prepared_path}" ] ; then
+        if ! goal network create --rootdir "${prepared_path}" --network 'private' \
+             --template "${template}" > "${logfile}" ; then
+            cat "${logfile}"
+            fatal "cannot generate network in '${prepared_path}'"
+        fi
+
+        kill_kmd_processes "${prepared_path}"
+        generate_chainconfig "${prepared_path}" "${nodefile}"
+        generate_algod_tokens "${prepared_path}" "${nodefile}"
+
+        rm "${prepared_path}/genesis.json"  # already in each node
+        rm "${prepared_path}/network.json"  # only used by goal network
+        rm "${prepared_path}/"*.rootkey*    # already in associated node
+        rm "${prepared_path}/"*.partkey*    # already in associated node
+    fi
+    cp -R "${prepared_path}" "${netroot}"
     set_goal_network_address "${netroot}" "${nodefile}"
     generate_start_scripts "${netroot}" "${nodefile}"
-    generate_algod_tokens "${netroot}" "${nodefile}"
-    generate_chainconfig "${netroot}" "${nodefile}"
 
-    rm "${netroot}/genesis.json"  # already in each node
-    rm "${netroot}/network.json"  # only used by goal network
-    rm "${netroot}/"*.rootkey     # already in associated node
-    rm "${netroot}/"*.partkey     # already in associated node
+    cp "${netroot}/accounts.yaml" "${deploy_root}/accounts.yaml"
 
     tar -C "${deploy_root}" -czf "${netroot}.tar.gz" 'network'
 }
