Fix Ethereum account generator build, use pre-built binaries for solc

diff --git a/script/remote/linux/apt/install-geth-accounts-worker b/script/remote/linux/apt/install-geth-accounts-worker
--- a/script/remote/linux/apt/install-geth-accounts-worker
+++ b/script/remote/linux/apt/install-geth-accounts-worker
@@ -13,6 +13,18 @@ if [ "x${number}" = 'x' ] ; then
     number=2
 fi
 
+if ! command -v 'sudo' > '/dev/null' ; then
+    echo "Cannot find command 'sudo'" >&2
+    exit 1
+fi
+
+while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
+    echo 'Waiting for release of dpkg/apt locks'
+    sleep 5
+done
+
+sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'gcc'
+
 # Create an install dir if not already there.
 #
 if [ ! -e 'install' ] ; then
